from collections.abc import Callable, Iterable
from types import ModuleType
from typing import Any, Generic

from typing_extensions import Self, TypeVar, override

from .core import Formula
from .operators import Bounds, M, M_ge, M_le, M_neg, M_neg_ge

class PanicException(Exception): ...

_T = TypeVar("_T", infer_variance=True)

class Top(Any):  # pyright: ignore[reportAny, reportExplicitAny]
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...

class Bottom(Any):  # pyright: ignore[reportAny, reportExplicitAny]
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...

class Trace(Generic[_T]):
    def __new__(cls, elements: dict[float, _T] | Trace[_T]) -> Self: ...
    def __getitem__(self, value: float) -> _T: ...
    def times(self) -> Iterable[float]: ...
    def states(self) -> Iterable[_T]: ...
    def at_time(self, time: float) -> _T | None: ...

class Predicate(Formula[dict[str, float], float]):
    def __new__(cls, coefficients: dict[str, float], constant: float) -> Self: ...
    @override
    def evaluate(self, trace: Trace[dict[str, float]]) -> Trace[float]: ...

_S = TypeVar("_S", infer_variance=True)

class Not(Formula[_S, M_neg]):
    def __new__(cls, subformula: Formula[_S, M_neg]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_neg]: ...

class And(Formula[_S, M_le]):
    def __new__(cls, lhs: Formula[_S, M_le], rhs: Formula[_S, M_le]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_le]: ...

class Or(Formula[_S, M_ge]):
    def __new__(cls, lhs: Formula[_S, M_ge], rhs: Formula[_S, M_ge]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_ge]: ...

class Implies(Formula[_S, M_neg_ge]):
    def __new__(cls, lhs: Formula[_S, M_neg_ge], rhs: Formula[_S, M_neg_ge]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_neg_ge]: ...

class Next(Formula[_S, M]):
    def __new__(cls, subformula: Formula[_S, M]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M]: ...

class Always(Formula[_S, M_le]):
    def __new__(cls, bounds: Bounds | None, subformula: Formula[_S, M_le]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_le]: ...

class Eventually(Formula[_S, M_ge]):
    def __new__(cls, bounds: Bounds | None, subformula: Formula[_S, M_ge]) -> Self: ...
    @override
    def evaluate(self, trace: Trace[_S]) -> Trace[M_ge]: ...

class _StlModule(ModuleType):
    class Formula(Formula[dict[str, float], float]): ...

    parse: Callable[[str], _StlModule.Formula]

stl: _StlModule
